### ISSUE TITLE
bucket crowdsecurity/ssh-bf with parsing errors

### ISSUE THREAD

**Issue by foulenzer** [crowdsecurity/hub#195]
Hello maintainers,

today I installed crowdsec on my ubuntu 20.04. It kinda works, but it has two problems with the bucket crowdsecurity/ssh-bf:

1.
# cscli decisions list
+-----+----------+-------------------+----------------------+--------+---------+------------------------+--------+--------------------+----------+
| ID  |  SOURCE  |    SCOPE:VALUE    |        REASON        | ACTION | COUNTRY |           AS           | EVENTS |     EXPIRATION     | ALERT ID |
+-----+----------+-------------------+----------------------+--------+---------+------------------------+--------+--------------------+----------+
| 402 | crowdsec | Ip:69.194.8.23    | crowdsecurity/ssh-bf | ban    | US      |  IT7 Networks Inc      |      6 | 3h55m56.161233828s |        6 |
| 301 | crowdsec | Ip:140.249.204.23 | crowdsecurity/ssh-bf | ban    | CN      |  No.31,Jin-rong Street |      6 | 3h54m42.066105083s |        4 |
+-----+----------+-------------------+----------------------+--------+---------+------------------------+--------+--------------------+----------+

The IPs listed are missing the last number of the last octet:

Apr 21 00:01:19 cs sshd[16536]: Invalid user citrus from 140.249.204.233 port 50223
Apr 21 00:01:19 cs sshd[16536]: Received disconnect from 140.249.204.233 port 50223:11: Bye Bye [preauth]
Apr 21 00:01:19 cs sshd[16536]: Disconnected from invalid user citrus 140.249.204.233 port 50223 [preauth]

Apr 21 00:07:14 cs sshd[16882]: Invalid user acacia from 69.194.8.237 port 58898
Apr 21 00:07:15 cs sshd[16882]: Received disconnect from 69.194.8.237 port 58898:11: Bye Bye [preauth]
Apr 21 00:07:15 cs sshd[16882]: Disconnected from invalid user acacia 69.194.8.237 port 58898 [preauth]

2.
I get some messages in the crowdsec.log:

time="21-04-2021 00:07:16" level=error msg="unable to collect sources from bucket: while extracting scope from bucket crowdsecurity/ssh-bf: scope is Ip but Meta[source_ip] doesn't exist"
time="21-04-2021 00:07:18" level=error msg="unable to collect sources from bucket: while extracting scope from bucket crowdsecurity/ssh-bf: scope is Ip but Meta[source_ip] doesn't exist"

I think the parser has problems with following lines.

Apr 21 00:07:17 cs sshd[16879]: error: PAM: Authentication failure for root from 221.131.165.56
Apr 21 00:07:17 cs sshd[16885]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=221.131.165.56  user=root

I feel very sorry, if these issues have been addressed yet, but I did not find them using the search function.

Best regards,
Ben

**Comment by foulenzer** [comment]
Further investigations lead to a more precise result:

1.
914 | crowdsec | Ip:140.143.229.20  | crowdsecurity/ssh-bf | ban    | CN      |  Shenzhen Tencent Computer     |      6 | 3h32m9.808421598s  |      122

Apr 21 07:34:20 cs sshd[20380]: Invalid user wedding from 140.143.229.207 port 47604
Apr 21 07:34:21 cs sshd[20380]: Received disconnect from 140.143.229.207 port 47604:11: Bye Bye [preauth]
Apr 21 07:34:21 cs sshd[20380]: Disconnected from invalid user wedding 140.143.229.207 port 47604 [preauth]


I think the parser only forgets the last digit, if the last octet contains 3 digits and starts with a "2", since he detects other IPs:

915 | crowdsec | Ip:42.192.235.102  | crowdsecurity/ssh-bf | ban    | CN      |                                |      6 | 3h43m36.213714062s |      123

**Comment by buixor** [comment]
Hello @foulenzer !

First of all, thanks for the report !
Investigated a bit, and it's a bit tricky, a fix is underway. For the record :

 - crowdsec uses [grokky](https://github.com/logrusorgru/grokky) for managing grok patterns
 - grokky itself defines (in the code) a pattern for IPV4 IPs that is as follows :

```
(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))
```
 - further testing reveals that this pattern might miss the last digit of the IP if it starts with `.2XX` but *only* if the captured item is the last in the regexp (`[0-1]?[0-9]{1,2}` will accept `2X` )
 - other libraries inspired from (or that inspired the author) seems to have fixed the pattern by [switching the faulty capture group position](https://github.com/vjeantet/grok/blob/53ca9634b5ed77b9c4ddb6690d6e6dffe195ac23/patterns/grok-patterns#L25)


After checking, this pattern is the only one that we have that might trigger this specific bug, cool that you found it !



Fixes :
 - *short term* We're fixing the [sshd parser](https://hub.crowdsec.net/author/crowdsecurity/configurations/sshd-logs) to avoid the edge case where it triggers the bug
 - *medium term* We're going to fix the regexp on crowdsec side (the library itself is not really maintained anymore), so that even in weird cases this won't happen

**Comment by foulenzer** [comment]
Hey blotus,

thank you very much for your answer and the useful software! I fell in love immediately. :-)

Best regards

**Comment by blotus** [comment]
Hello @foulenzer,

The fix has just been merged.
You can upgrade the ssh parser by running `cscli hub update && cscli parsers upgrade crowdsecurity/sshd-logs && systemctl reload crowdsec.service` if you are running the latest stable release (1.0.9).

**Comment by foulenzer** [comment]
Hey @blotus,

perfect, thanks again for your message and the fast fix. ☺️
